name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: CollimationCircles.sln                     # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2    
      
    - name: Install dependencies
      run: dotnet restore
        
    - name: Publish Win x64
      run: |
        dotnet build --configuration $env:Configuration --no-restore
        dotnet publish -c $env:Configuration -o ../CC/win-x64 -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true
      
    #- name: Publish Linux x64
    #  run: dotnet publish -c $env:Configuration -o ../CC/linux-x64 -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true
      
    #- name: Publish Linux arm64
    #  run: dotnet publish -c $env:Configuration -o ../CC/linux-arm64 -r linux-arm64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true
